-- ============================================================
-- 02_orders.sql -- 2026-05-25 사용자 요구로 ORDER 데이터 전부 제거
--
-- ORDER_* 4 테이블 (ORDER_OS / ORDER_OM / ORDER_QD / ORDER_CHEMICAL) 모두 비움.
-- SLAB_RESULT / SLAB_DESIGN_HIST 도 SeedService.TABLES TRUNCATE 단계에서 비워짐.
--
-- 시뮬레이션 에이전트가 실제 주문 데이터에 의존하지 않고, ontology + 풍부한 기준
-- 데이터(01_master.sql) 만으로 가상 주문을 합성 → 21-step 시뮬을 수행하도록 함.
-- 실측 검증이 필요하면 별도 fixture(POST /api/sd/seed/reset 이후 직접 INSERT) 로 주입.
-- ============================================================

-- (의도적으로 INSERT 없음)
