"""AUTO-GENERATED BY scripts/codegen_patch_models.py — DO NOT EDIT.

Source of truth: toClaude/modeling/editable_fields.yaml
Regenerate with:  python scripts/codegen_patch_models.py
"""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class TermPatch(BaseModel):
    """PATCH body for Term. None = field unchanged."""
    label: str | None = Field(default=None, max_length=200)
    aliases: list[str] | None = Field(default=None)
    description: str | None = Field(default=None, max_length=4000)
    domain: str | None = Field(default=None, max_length=80)
    value_type: str | None = Field(default=None, max_length=80)
    unit: str | None = Field(default=None, max_length=40)
    range: list[float] | None = Field(default=None)
    enum_values: list[str] | None = Field(default=None)

class ActionPatch(BaseModel):
    """PATCH body for Action. None = field unchanged."""
    label: str | None = Field(default=None, max_length=200)
    aliases: list[str] | None = Field(default=None)
    description: str | None = Field(default=None, max_length=4000)

class BRPatch(BaseModel):
    """PATCH body for BusinessRule. None = field unchanged."""
    statement: str | None = Field(default=None, min_length=1, max_length=8000)
    severity: Literal['hard', 'soft'] | None = Field(default=None)

class AnchorPatch(BaseModel):
    """PATCH body for AnchorBinding. None = field unchanged."""
    anchor_locator: str | None = Field(default=None, max_length=200)
    target_slot: str | None = Field(default=None, max_length=200)
    rationale: str | None = Field(default=None, max_length=4000)

class CodeTypePatch(BaseModel):
    """PATCH body for CodeType. None = field unchanged."""
    role: Literal['domain', 'framework', 'infra', 'unknown'] | None = Field(default=None)

# Generic dispatch table (entity_name → Patch class)
ENTITY_TO_PATCH = {
    'Term': TermPatch,
    'Action': ActionPatch,
    'BusinessRule': BRPatch,
    'AnchorBinding': AnchorPatch,
    'CodeType': CodeTypePatch,
}

__all__ = (
    'TermPatch',
    'ActionPatch',
    'BRPatch',
    'AnchorPatch',
    'CodeTypePatch',
    "ENTITY_TO_PATCH",
)
