"""Generated by PythonGenerator (echo-stub, spec 05 §1.3 단순화).

ChangeSpec.action_fqn       : action.scm.resolve_and_set
RunPlan.estimated_steps     : 1
RunPlan.delegates_to_tree.size : 1

atomic_overrides:
  (none)

본 코드는 PythonGenerator 가 합성한 텍스트 — 직접 실행 금지.
sandbox 가 import 화이트리스트 검증 후 exec/ast-execute (spec 05 §1.4).
"""

from backend.shared.contracts.simulation import DelegationTraceFrame


def run(inputs, java_sandbox, lookup_source, run_options):
    """ECHO-STUB run() — orchestrator (3b-4) 가 보강 예정.

    Args:
        inputs           : RunInputs (slots / fixture / overrides / primary_input_slot)
        java_sandbox     : JavaSandbox 구현체 (StubJavaSandbox 등)
        lookup_source    : LookupDataSource 인스턴스
        run_options      : RunOptions

    Returns:
        dict — {"trace": list[DelegationTraceFrame], "outputs": dict}
    """
    trace: list = []
    # delegation frame 1 (depth=0) — echo-stub sequential
    _result_1 = java_sandbox.dispatch('action.scm.resolve_and_set', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=0,
        action_fqn='action.scm.resolve_and_set',
        realized_method_fqn=_result_1.realized_method_fqn,
        dispatch_consistent=_result_1.dispatch_consistent,
        dispatch_mismatch_reason=_result_1.dispatch_mismatch_reason,
        duration_ms=_result_1.duration_ms,
    ))

    return {"trace": trace, "outputs": {}}
