// AUTO-GENERATED BY scripts/codegen_inline_wiring.py — DO NOT EDIT.
// Source of truth: toClaude/modeling/editable_fields.yaml
// Regenerate with:  python scripts/codegen_inline_wiring.py

export type EditKind =
  | "inline_text"
  | "inline_textarea"
  | "inline_list"
  | "inline_select"
  | "inline_autocomplete"
  | "inline_number"
  | "inline_range"
  | "read_only"
  | "authoring_only";

export interface EditOpts {
  confirm_modal?: boolean;
  options?: string[];
  fallback_text?: boolean;
  autocomplete_source?: string;
  min?: number;
  max?: number;
  step?: number;
  rows?: number;
}

export interface ValidationOpts {
  min_length?: number;
  max_length?: number;
  regex?: string;
  one_of?: string[];
}

export interface EditConfig {
  kind: EditKind;
  /** key sent in the PATCH body (defaults to field name) */
  patch_key: string;
  /** ORM column name — diagnostic only, not used at runtime */
  backend_column: string;
  edit_opts?: EditOpts;
  validation?: ValidationOpts;
  /** if set, field is derived from another path; UI shows it read-only */
  derived_from?: string;
  /** for fields with auto + user-override duality (#8 CodeType.role) */
  confidence_label?: "auto" | "mixed" | "user_only";
}

export type EntityName =

  | "Term"
  | "Action"
  | "BusinessRule"
  | "AnchorBinding"
  | "CodeType";

export const EDITABLE_FIELDS: Record<EntityName, Record<string, EditConfig>> = {
  "Term": {
    "fqn": {
      "kind": "read_only",
      "patch_key": "fqn",
      "backend_column": "fqn"
    },
    "repo_id": {
      "kind": "read_only",
      "patch_key": "repo_id",
      "backend_column": "repo_id"
    },
    "label": {
      "kind": "inline_text",
      "patch_key": "label",
      "backend_column": "label",
      "validation": {
        "max_length": 200
      }
    },
    "aliases": {
      "kind": "inline_list",
      "patch_key": "aliases",
      "backend_column": "aliases_json"
    },
    "description": {
      "kind": "inline_textarea",
      "patch_key": "description",
      "backend_column": "description",
      "edit_opts": {
        "rows": 3
      },
      "validation": {
        "max_length": 4000
      }
    },
    "domain": {
      "kind": "inline_text",
      "patch_key": "domain",
      "backend_column": "domain",
      "validation": {
        "max_length": 80
      }
    },
    "value_type": {
      "kind": "inline_select",
      "patch_key": "value_type",
      "backend_column": "value_type",
      "edit_opts": {
        "options": [
          "string",
          "int",
          "long",
          "float",
          "double",
          "boolean",
          "decimal",
          "date",
          "datetime",
          "uuid",
          "bytes",
          "enum"
        ],
        "fallback_text": true
      },
      "validation": {
        "max_length": 80
      }
    },
    "unit": {
      "kind": "inline_text",
      "patch_key": "unit",
      "backend_column": "unit",
      "validation": {
        "max_length": 40
      }
    },
    "range": {
      "kind": "inline_range",
      "patch_key": "range",
      "backend_column": "range_json",
      "edit_opts": {
        "step": 0.01
      }
    },
    "enum_values": {
      "kind": "inline_list",
      "patch_key": "enum_values",
      "backend_column": "enum_values_json"
    },
    "kind": {
      "kind": "read_only",
      "patch_key": "kind",
      "backend_column": "kind",
      "validation": {
        "one_of": [
          "atomic",
          "composite"
        ]
      }
    },
    "is_abstract": {
      "kind": "read_only",
      "patch_key": "is_abstract",
      "backend_column": "is_abstract"
    },
    "is_interface": {
      "kind": "read_only",
      "patch_key": "is_interface",
      "backend_column": "is_interface"
    },
    "is_root_entity": {
      "kind": "read_only",
      "patch_key": "is_root_entity",
      "backend_column": "is_root_entity"
    },
    "struct_like_hint": {
      "kind": "read_only",
      "patch_key": "struct_like_hint",
      "backend_column": "struct_like_hint"
    },
    "confirmed": {
      "kind": "read_only",
      "patch_key": "confirmed",
      "backend_column": "confirmed"
    },
  },
  "Action": {
    "fqn": {
      "kind": "read_only",
      "patch_key": "fqn",
      "backend_column": "fqn"
    },
    "repo_id": {
      "kind": "read_only",
      "patch_key": "repo_id",
      "backend_column": "repo_id"
    },
    "label": {
      "kind": "inline_text",
      "patch_key": "label",
      "backend_column": "label",
      "validation": {
        "max_length": 200
      }
    },
    "aliases": {
      "kind": "inline_list",
      "patch_key": "aliases",
      "backend_column": "aliases_json"
    },
    "description": {
      "kind": "inline_textarea",
      "patch_key": "description",
      "backend_column": "description",
      "edit_opts": {
        "rows": 3
      },
      "validation": {
        "max_length": 4000
      }
    },
    "domain": {
      "kind": "read_only",
      "patch_key": "domain",
      "backend_column": "domain",
      "derived_from": "declared_on_term.domain"
    },
    "kind": {
      "kind": "authoring_only",
      "patch_key": "kind",
      "backend_column": "kind",
      "validation": {
        "one_of": [
          "pure_function",
          "effectful",
          "workflow"
        ]
      }
    },
    "is_abstract": {
      "kind": "read_only",
      "patch_key": "is_abstract",
      "backend_column": "is_abstract"
    },
    "declared_on_term": {
      "kind": "authoring_only",
      "patch_key": "declared_on_term",
      "backend_column": "declared_on_term"
    },
    "params": {
      "kind": "authoring_only",
      "patch_key": "params",
      "backend_column": "params_json"
    },
    "output": {
      "kind": "authoring_only",
      "patch_key": "output",
      "backend_column": "output_json"
    },
    "preconditions": {
      "kind": "authoring_only",
      "patch_key": "preconditions",
      "backend_column": "preconditions_json"
    },
    "postconditions": {
      "kind": "authoring_only",
      "patch_key": "postconditions",
      "backend_column": "postconditions_json"
    },
    "effects": {
      "kind": "authoring_only",
      "patch_key": "effects",
      "backend_column": "effects_json"
    },
    "sub_actions": {
      "kind": "authoring_only",
      "patch_key": "sub_actions",
      "backend_column": "sub_actions_json"
    },
    "verification_level": {
      "kind": "read_only",
      "patch_key": "verification_level",
      "backend_column": "verification_level",
      "validation": {
        "one_of": [
          "unmapped",
          "draft",
          "signature_locked",
          "body_anchored",
          "sim_verified",
          "pr_proven"
        ]
      }
    },
    "signature_locked_at": {
      "kind": "read_only",
      "patch_key": "signature_locked_at",
      "backend_column": "signature_locked_at"
    },
    "confirmed_by": {
      "kind": "read_only",
      "patch_key": "confirmed_by",
      "backend_column": "confirmed_by"
    },
  },
  "BusinessRule": {
    "fqn": {
      "kind": "read_only",
      "patch_key": "fqn",
      "backend_column": "fqn"
    },
    "repo_id": {
      "kind": "read_only",
      "patch_key": "repo_id",
      "backend_column": "repo_id"
    },
    "statement": {
      "kind": "inline_textarea",
      "patch_key": "statement",
      "backend_column": "statement",
      "edit_opts": {
        "rows": 4
      },
      "validation": {
        "min_length": 1,
        "max_length": 8000
      }
    },
    "severity": {
      "kind": "inline_select",
      "patch_key": "severity",
      "backend_column": "severity",
      "edit_opts": {
        "options": [
          "hard",
          "soft"
        ],
        "confirm_modal": true
      },
      "validation": {
        "one_of": [
          "hard",
          "soft"
        ]
      }
    },
    "terms_ref": {
      "kind": "authoring_only",
      "patch_key": "terms_ref",
      "backend_column": "terms_ref_json"
    },
    "enforced_by": {
      "kind": "read_only",
      "patch_key": "enforced_by",
      "backend_column": "enforced_by_json"
    },
    "violated_at_call": {
      "kind": "read_only",
      "patch_key": "violated_at_call",
      "backend_column": "violated_at_call_json"
    },
    "operational_history": {
      "kind": "read_only",
      "patch_key": "operational_history",
      "backend_column": "operational_history_json"
    },
    "source": {
      "kind": "read_only",
      "patch_key": "source",
      "backend_column": "source"
    },
    "confirmed": {
      "kind": "read_only",
      "patch_key": "confirmed",
      "backend_column": "confirmed"
    },
  },
  "AnchorBinding": {
    "id": {
      "kind": "read_only",
      "patch_key": "id",
      "backend_column": "id"
    },
    "repo_id": {
      "kind": "read_only",
      "patch_key": "repo_id",
      "backend_column": "repo_id"
    },
    "anchor_locator": {
      "kind": "inline_autocomplete",
      "patch_key": "anchor_locator",
      "backend_column": "anchor_locator",
      "edit_opts": {
        "autocomplete_source": "/api/ontology/code-methods/{code_method_fqn}/fragments"
      },
      "validation": {
        "max_length": 200
      }
    },
    "target_slot": {
      "kind": "inline_text",
      "patch_key": "target_slot",
      "backend_column": "target_slot",
      "validation": {
        "max_length": 200
      }
    },
    "rationale": {
      "kind": "inline_textarea",
      "patch_key": "rationale",
      "backend_column": "rationale",
      "edit_opts": {
        "rows": 3
      },
      "validation": {
        "max_length": 4000
      }
    },
    "code_method_fqn": {
      "kind": "read_only",
      "patch_key": "code_method_fqn",
      "backend_column": "code_method_fqn"
    },
    "target_action_fqn": {
      "kind": "read_only",
      "patch_key": "target_action_fqn",
      "backend_column": "target_action_fqn"
    },
    "confidence": {
      "kind": "read_only",
      "patch_key": "confidence",
      "backend_column": "confidence"
    },
    "source": {
      "kind": "read_only",
      "patch_key": "source",
      "backend_column": "source"
    },
    "confirmed": {
      "kind": "read_only",
      "patch_key": "confirmed",
      "backend_column": "confirmed"
    },
    "line": {
      "kind": "read_only",
      "patch_key": "line",
      "backend_column": "line"
    },
  },
  "CodeType": {
    "fqn": {
      "kind": "read_only",
      "patch_key": "fqn",
      "backend_column": "fqn"
    },
    "repo_id": {
      "kind": "read_only",
      "patch_key": "repo_id",
      "backend_column": "repo_id"
    },
    "role": {
      "kind": "inline_select",
      "patch_key": "role",
      "backend_column": "role",
      "confidence_label": "mixed",
      "edit_opts": {
        "options": [
          "domain",
          "framework",
          "infra",
          "unknown"
        ]
      },
      "validation": {
        "one_of": [
          "domain",
          "framework",
          "infra",
          "unknown"
        ]
      }
    },
    "simple_name": {
      "kind": "read_only",
      "patch_key": "simple_name",
      "backend_column": "simple_name"
    },
    "package": {
      "kind": "read_only",
      "patch_key": "package",
      "backend_column": "package"
    },
    "kind": {
      "kind": "read_only",
      "patch_key": "kind",
      "backend_column": "kind",
      "validation": {
        "one_of": [
          "class",
          "abstract_class",
          "interface",
          "enum",
          "record"
        ]
      }
    },
    "is_abstract": {
      "kind": "read_only",
      "patch_key": "is_abstract",
      "backend_column": "is_abstract"
    },
    "extends": {
      "kind": "read_only",
      "patch_key": "extends",
      "backend_column": "extends"
    },
    "implements": {
      "kind": "read_only",
      "patch_key": "implements",
      "backend_column": "implements_json"
    },
    "extends_interfaces": {
      "kind": "read_only",
      "patch_key": "extends_interfaces",
      "backend_column": "extends_interfaces_json"
    },
    "modifiers": {
      "kind": "read_only",
      "patch_key": "modifiers",
      "backend_column": "modifiers_json"
    },
    "annotations": {
      "kind": "read_only",
      "patch_key": "annotations",
      "backend_column": "annotations_json"
    },
    "source_file": {
      "kind": "read_only",
      "patch_key": "source_file",
      "backend_column": "source_file"
    },
    "line_start": {
      "kind": "read_only",
      "patch_key": "line_start",
      "backend_column": "line_start"
    },
    "line_end": {
      "kind": "read_only",
      "patch_key": "line_end",
      "backend_column": "line_end"
    },
  },
};

export function getEditConfig(
  entity: EntityName | string,
  field: string,
): EditConfig | null {
  const e = (EDITABLE_FIELDS as Record<string, Record<string, EditConfig>>)[entity];
  if (!e) return null;
  return e[field] ?? null;
}

/** Convenience: list of all entities for iteration */
export const ENTITIES: ReadonlyArray<EntityName> = ["Term", "Action", "BusinessRule", "AnchorBinding", "CodeType"] as const;
