slab:
  equipment:
    rolling-mill-max-width-mm: 2400.0
    furnace-max-length-mm: 12000.0
    crane-max-load-kg: 45000.0
    min-thickness-mm: 180.0
    max-thickness-mm: 240.0

server:
  port: 8090
