"""Agent 2 — 테스트 데이터 생성 + 샌드박스 실행.

Phase 2: Hypothesis 기반 case 생성 → subprocess 격리 실행 → 결과 분석.
SSE 스트리밍과 동기 호출 둘 다 지원.

기존 v1 (Section 2 ontology의 SIMULATE intent에 위임)은 폐기.
"""

from __future__ import annotations

import asyncio
import json
import logging
import time
import uuid
from typing import AsyncIterator, Literal, Optional

from pydantic import BaseModel, Field

from ..sandbox.runner import run_in_subprocess
from ..testgen import case_builder
from ..testgen.case_builder import CaseOutcome, CaseSpec
from ..testgen.hypothesis_strategies import CaseType


logger = logging.getLogger(__name__)


# ─── 입력 / 출력 스키마 ─────────────────────────────────────────────


class Agent2Request(BaseModel):
    """Agent 2 호출 페이로드.

    target_id에서 step_id를 추출:
    - "step_9" / "9" / "slab_count" / "pipeline" 등 sandbox registry 키.
    - 호환성을 위해 Phase 1의 step_X 라벨도 매핑 (case_builder 측 미들웨어).
    """

    target_type: Literal["step", "method", "standard"] = "step"
    target_id: str
    case_types: list[CaseType] = Field(default_factory=lambda: ["normal", "boundary", "error"])
    test_count: int = 5
    rules: dict[str, str] = Field(default_factory=dict)
    """변형 룰. 예: {"hr": "0.92", "hrf": "0.85"}. pipeline step에서만 의미."""


class TestCaseDoc(BaseModel):
    """단일 case 결과 (REST/SSE 양쪽 공용)."""

    case_id: str
    case_type: str
    description: str
    input_data: dict = Field(default_factory=dict)
    expected_output: dict = Field(default_factory=dict)
    actual_output: dict = Field(default_factory=dict)
    sandbox_ok: bool = True
    matches_expectation: bool = True
    elapsed_ms: int = 0
    error: Optional[dict] = None


class Agent2Result(BaseModel):
    """동기 호출 결과."""

    request_id: str
    status: Literal["success", "partial", "error"] = "success"
    summary: str = ""
    step_id: str = ""
    test_cases: list[TestCaseDoc] = Field(default_factory=list)
    statistics: dict = Field(default_factory=dict)
    code_skeleton: str = ""


# ─── step_id 정규화 ─────────────────────────────────────────────────


_LEGACY_STEP_MAP = {
    # 이전 ontology label → sandbox registry key
    "step_1": "thickness",
    "step_8": "split_range",
    "step_9": "slab_count",
    "step_10": "slab_weight",
}

_VALID_SANDBOX_STEPS = {
    "validator", "productivity", "thickness",
    "split_range", "slab_count", "slab_weight", "pipeline",
}


def _resolve_step_id(target_id: str) -> str:
    if target_id in _VALID_SANDBOX_STEPS:
        return target_id
    if target_id in _LEGACY_STEP_MAP:
        return _LEGACY_STEP_MAP[target_id]
    # "9" or "step_X" 둘 다 처리
    digit = target_id.replace("step_", "")
    if digit.isdigit():
        n = int(digit)
        return {1: "thickness", 8: "split_range", 9: "slab_count", 10: "slab_weight"}.get(
            n, "pipeline"
        )
    # 미지의 라벨은 pipeline (가장 풍부한 e2e 결과)
    return "pipeline"


# ─── 코드 스켈레톤 (사용자 다운로드용) ────────────────────────────────


def _generate_code_skeleton(step_id: str, fail_cases: list[dict]) -> str:
    """실패 케이스를 pytest로 재현할 수 있는 코드 스켈레톤."""
    lines = [
        '"""Auto-generated by onTong Agent 2 — slab-design sandbox 재현 스니펫."""',
        "from __future__ import annotations",
        "",
        "import pytest",
        "from backend.simulation.sandbox.runner import run_in_subprocess",
        "",
        "",
    ]
    if not fail_cases:
        lines.extend([
            f"def test_{step_id}_passes_normal_case():",
            f'    r = run_in_subprocess("{step_id}", {{}})',
            "    assert r.ok",
            "",
        ])
        return "\n".join(lines)

    for i, fc in enumerate(fail_cases[:5]):
        lines.append(f"def test_{step_id}_fail_case_{i+1}():")
        lines.append(f'    """{fc.get("description", "")}"""')
        lines.append(f'    inputs = {json.dumps(fc.get("inputs", {}), ensure_ascii=False)}')
        lines.append(f'    r = run_in_subprocess("{step_id}", inputs)')
        if fc.get("expected", {}).get("dg"):
            lines.append(f'    assert r.result["validation"]["error_code"] == "{fc["expected"]["dg"]}"')
        else:
            lines.append("    assert r.ok is True")
        lines.append("")
    return "\n".join(lines)


# ─── 동기 실행 (호환용) ─────────────────────────────────────────────


async def execute_agent2(req: Agent2Request) -> Agent2Result:
    """동기 결과 반환 — 작은 N (예: ≤ 50)에 적합. SSE는 별도."""
    request_id = str(uuid.uuid4())
    step_id = _resolve_step_id(req.target_id)
    test_count = max(1, min(req.test_count, 200))  # 동기 cap 200

    cases = case_builder.build_cases(
        step_id=step_id,
        case_types=req.case_types,
        count_per_type=test_count,
        rules=req.rules or None,
    )

    # subprocess 비용이 있으므로 동기 path는 thread off-load
    loop = asyncio.get_running_loop()

    async def _run_one(case: CaseSpec) -> CaseOutcome:
        result = await loop.run_in_executor(
            None,
            lambda: run_in_subprocess(step_id, case.sandbox_inputs, timeout_sec=5),
        )
        return case_builder.analyze_outcome(case, result)

    outcomes = await asyncio.gather(*(_run_one(c) for c in cases))
    summary = case_builder.summarize(outcomes)

    docs = [_outcome_to_doc(o) for o in outcomes]
    skeleton = _generate_code_skeleton(step_id, summary.get("fail_cases", []))

    status: Literal["success", "partial", "error"]
    if summary["failed_count"] == 0:
        status = "success"
    elif summary["failed_count"] < summary["total"]:
        status = "partial"
    else:
        status = "error"

    return Agent2Result(
        request_id=request_id,
        status=status,
        step_id=step_id,
        summary=(
            f"step={step_id}, {summary['total']}건 실행, "
            f"{summary['failed_count']}건 기대 불일치"
        ),
        test_cases=docs,
        statistics=summary,
        code_skeleton=skeleton,
    )


def _outcome_to_doc(o: CaseOutcome) -> TestCaseDoc:
    return TestCaseDoc(
        case_id=o.case_id,
        case_type=o.case_type,
        description=o.description,
        input_data=o.inputs,
        expected_output=o.expected,
        actual_output=o.sandbox_result or {},
        sandbox_ok=o.sandbox_ok,
        matches_expectation=o.matches_expectation,
        elapsed_ms=o.elapsed_ms,
        error=o.sandbox_error,
    )


# ─── SSE 스트리밍 ───────────────────────────────────────────────────


async def stream_agent2(req: Agent2Request) -> AsyncIterator[dict]:
    """SSE 이벤트 generator.

    이벤트 종류:
    - run_started: {request_id, step_id, total}
    - case_started: {case_id, case_type, idx}
    - case_done: {case_id, matches_expectation, elapsed_ms, summary_payload}
    - case_failed: case_done과 동일하나 matches_expectation=False
    - summary: {total, failed_count, by_type, slab_count_distribution, productivity_distribution, fail_cases, code_skeleton}
    - run_complete
    """
    request_id = str(uuid.uuid4())
    step_id = _resolve_step_id(req.target_id)
    test_count = max(1, min(req.test_count, 1000))  # SSE cap 1000

    cases = case_builder.build_cases(
        step_id=step_id,
        case_types=req.case_types,
        count_per_type=test_count,
        rules=req.rules or None,
    )

    yield {
        "event": "run_started",
        "data": {
            "request_id": request_id,
            "step_id": step_id,
            "total": len(cases),
            "case_types": req.case_types,
            "rules": req.rules,
        },
    }

    loop = asyncio.get_running_loop()
    queue: asyncio.Queue = asyncio.Queue()

    # 병렬 실행 — 4 워커 정도가 적정 (subprocess는 메모리 비용 있음)
    sem = asyncio.Semaphore(4)
    outcomes_list: list[CaseOutcome] = []

    async def _runner_with_collect(idx: int, case: CaseSpec) -> None:
        async with sem:
            await queue.put({
                "event": "case_started",
                "data": {"idx": idx, "case_id": case.case_id, "case_type": case.case_type,
                         "description": case.description},
            })
            started = time.perf_counter()
            result = await loop.run_in_executor(
                None,
                lambda: run_in_subprocess(step_id, case.sandbox_inputs, timeout_sec=5),
            )
            elapsed_ms = int((time.perf_counter() - started) * 1000)
            outcome = case_builder.analyze_outcome(case, result)
            outcome.elapsed_ms = max(outcome.elapsed_ms, elapsed_ms)
            outcomes_list.append(outcome)

            await queue.put({
                "event": "case_done" if outcome.matches_expectation else "case_failed",
                "data": _outcome_event_payload(outcome),
            })

    async def _drive_all() -> None:
        await asyncio.gather(*(_runner_with_collect(i, c) for i, c in enumerate(cases)))
        await queue.put(None)  # sentinel

    drive_task = asyncio.create_task(_drive_all())

    while True:
        item = await queue.get()
        if item is None:
            break
        yield item

    await drive_task

    summary = case_builder.summarize(outcomes_list)
    skeleton = _generate_code_skeleton(step_id, summary.get("fail_cases", []))

    # Phase 5: Risk Heatmap 데이터 첨부 (Java 파일 + 라인 마커)
    heatmap_payload = None
    try:
        from ..visualization.heatmap import build_heatmap, heatmap_to_json
        outcomes_for_hm = [
            {"sandbox_result": o.sandbox_result} for o in outcomes_list
        ]
        hm = build_heatmap(step_id, outcomes_for_hm)
        if hm is not None:
            heatmap_payload = heatmap_to_json(hm)
    except Exception as exc:  # noqa: BLE001
        logger.warning("heatmap build failed: %s", exc)

    yield {
        "event": "summary",
        "data": {
            **summary,
            "code_skeleton": skeleton,
            "step_id": step_id,
            "request_id": request_id,
            "heatmap": heatmap_payload,
        },
    }
    yield {"event": "run_complete", "data": {"request_id": request_id}}


def _outcome_event_payload(o: CaseOutcome) -> dict:
    return {
        "case_id": o.case_id,
        "case_type": o.case_type,
        "description": o.description,
        "matches_expectation": o.matches_expectation,
        "elapsed_ms": o.elapsed_ms,
        "input_data": o.inputs,
        "expected": o.expected,
        "actual_output": o.sandbox_result or {},
        "error": o.sandbox_error,
    }
