"""Generated by PythonGenerator (echo-stub, spec 05 §1.3 단순화).

ChangeSpec.action_fqn       : action.demo
RunPlan.estimated_steps     : 0
RunPlan.delegates_to_tree.size : 0

atomic_overrides:
  - path.x = 1180

본 코드는 PythonGenerator 가 합성한 텍스트 — 직접 실행 금지.
sandbox 가 import 화이트리스트 검증 후 exec/ast-execute (spec 05 §1.4).
"""

from backend.shared.contracts.simulation import DelegationTraceFrame


def run(inputs, java_sandbox, lookup_source, run_options):
    """ECHO-STUB run() — orchestrator (3b-4) 가 보강 예정.

    Args:
        inputs           : RunInputs (slots / fixture / overrides / primary_input_slot)
        java_sandbox     : JavaSandbox 구현체 (StubJavaSandbox 등)
        lookup_source    : LookupDataSource 인스턴스
        run_options      : RunOptions

    Returns:
        dict — {"trace": list[DelegationTraceFrame], "outputs": dict}
    """
    trace: list = []
    # 빈 delegation tree — 단순 echo 종료
    pass

    return {"trace": trace, "outputs": {}}
