"""PythonGenerator (spec 05 §1) — ChangeSpec + RunPlan → 실행 가능 Python 코드.

본 모듈은 spec 05 §1.3 의 echo-stub 단순화 구현 (첫 iteration):
- delegates_to_tree 를 flat 순차 dispatch loop 로 emit
- loop / optional 처리는 후속 step (3b-4 orchestrator + atomic.facets 활용)
- atomic_overrides 는 헤더 docstring 으로 echo (적용은 orchestrator 가)
- import 화이트리스트 (spec 05 §1.4): simulation contracts + java_sandbox / lookup_source

생성된 코드는 본 모듈 자체가 실행하지 않는다 — orchestrator (3b-4) 가
exec() 또는 ast 기반 안전 실행으로 처리.
"""

from __future__ import annotations

import logging
from typing import Any

from backend.shared.contracts.simulation import (
    ChangeSpec,
    GeneratedScript,
    RunPlan,
)

logger = logging.getLogger(__name__)


# ─── PythonGenerator (spec 05 §1.2 echo-stub) ──────────────────────


class PythonGenerator:
    """RunPlan → GeneratedScript 합성. echo-stub (첫 iter):
    - delegates_to_tree 의 모든 frame 을 sequential dispatch 로 emit
    - loop / optional 은 후속 step 에서 보강 (현재는 무시 — 일반 dispatch 로 처리)
    - atomic_overrides 는 헤더 docstring 에 echo
    """

    _IMPORTS = [
        "from backend.shared.contracts.simulation import DelegationTraceFrame",
    ]

    def generate(
        self,
        change_spec: ChangeSpec,
        run_plan: RunPlan,
    ) -> GeneratedScript:
        """spec 05 §1.2 — GeneratedScript 합성.

        Steps (echo-stub):
          1. delegation tree 의 action_fqn 추출 + dedup
          2. fixture key 추출
          3. source code 합성 (헤더 docstring + run() 함수)
          4. estimated_steps 전파
        """
        action_fqns = self._extract_action_fqns(run_plan)
        fixture_keys = self._extract_fixture_keys(change_spec)
        source_code = self._build_source_code(change_spec, run_plan, action_fqns)

        return GeneratedScript(
            source_code=source_code,
            entrypoint="run",
            imports=list(self._IMPORTS),
            estimated_steps=run_plan.estimated_steps,
            java_dispatch_calls=action_fqns,
            fixture_keys_used=fixture_keys,
        )

    # ─── 내부 — meta 추출 ─────────────────────────────────────────

    @staticmethod
    def _extract_action_fqns(run_plan: RunPlan) -> list[str]:
        """delegates_to_tree 의 action_fqn 추출 + 첫 등장 순 dedup."""
        seen: set[str] = set()
        result: list[str] = []
        for edge in run_plan.delegates_to_tree:
            fqn = edge.get("action_fqn") if isinstance(edge, dict) else None
            if fqn is None:
                logger.debug("delegation edge without action_fqn — skip: %r", edge)
                continue
            if fqn in seen:
                continue
            seen.add(fqn)
            result.append(fqn)
        return result

    @staticmethod
    def _extract_fixture_keys(change_spec: ChangeSpec) -> list[str]:
        """ChangeSpec.scenario_fixture.lookups 의 key 목록 (정렬은 caller 가)."""
        lookups = change_spec.scenario_fixture.get("lookups", {}) or {}
        if not isinstance(lookups, dict):
            return []
        return list(lookups.keys())

    # ─── 내부 — source code 합성 ─────────────────────────────────

    @classmethod
    def _build_source_code(
        cls,
        change_spec: ChangeSpec,
        run_plan: RunPlan,
        action_fqns: list[str],
    ) -> str:
        """헤더 docstring + import + run() 함수.

        체크리스트:
        - ast.parse 통과
        - blacklist 모듈 (os/subprocess/socket/pickle) import 없음
        - 각 action_fqn 이 dispatch call 의 string literal 로 등장
        """
        header = cls._build_header(change_spec, run_plan)
        imports = "\n".join(cls._IMPORTS)
        body = cls._build_run_body(run_plan)

        return f'''{header}
{imports}


def run(inputs, java_sandbox, lookup_source, run_options):
    """ECHO-STUB run() — orchestrator (3b-4) 가 보강 예정.

    Args:
        inputs           : RunInputs (slots / fixture / overrides / primary_input_slot)
        java_sandbox     : JavaSandbox 구현체 (StubJavaSandbox 등)
        lookup_source    : LookupDataSource 인스턴스
        run_options      : RunOptions

    Returns:
        dict — {{"trace": list[DelegationTraceFrame], "outputs": dict}}
    """
    trace: list = []
{body}
    return {{"trace": trace, "outputs": {{}}}}
'''

    @staticmethod
    def _build_header(change_spec: ChangeSpec, run_plan: RunPlan) -> str:
        """파일 헤더 docstring — change_spec 메타 echo."""
        overrides_lines = [
            f"  - {path} = {value!r}"
            for path, value in change_spec.atomic_overrides.items()
        ]
        overrides_block = "\n".join(overrides_lines) if overrides_lines else "  (none)"
        return f'''"""Generated by PythonGenerator (echo-stub, spec 05 §1.3 단순화).

ChangeSpec.action_fqn       : {change_spec.action_fqn}
RunPlan.estimated_steps     : {run_plan.estimated_steps}
RunPlan.delegates_to_tree.size : {len(run_plan.delegates_to_tree)}

atomic_overrides:
{overrides_block}

본 코드는 PythonGenerator 가 합성한 텍스트 — 직접 실행 금지.
sandbox 가 import 화이트리스트 검증 후 exec/ast-execute (spec 05 §1.4).
"""
'''

    @staticmethod
    def _build_run_body(run_plan: RunPlan) -> str:
        """run() 본문 — 각 delegation edge 를 dispatch + trace.append 로 emit.

        echo-stub: loop/optional 무시 — 일반 sequential dispatch 로 처리.
        후속 step 에서 is_in_loop / optional 분기 추가.
        """
        if not run_plan.delegates_to_tree:
            return "    # 빈 delegation tree — 단순 echo 종료\n    pass\n"

        lines: list[str] = []
        for i, edge in enumerate(run_plan.delegates_to_tree, start=1):
            fqn = edge.get("action_fqn") if isinstance(edge, dict) else None
            depth = edge.get("depth", 0) if isinstance(edge, dict) else 0
            if fqn is None:
                lines.append(f"    # frame {i}: action_fqn missing — skip")
                continue
            # dispatch + trace.append (DelegationTraceFrame schema 와 정합)
            lines.append(
                f'    # delegation frame {i} (depth={depth}) — echo-stub sequential\n'
                f'    _result_{i} = java_sandbox.dispatch({fqn!r}, inputs, run_options)\n'
                f'    trace.append(DelegationTraceFrame(\n'
                f'        seq=len(trace) + 1,\n'
                f'        depth={depth},\n'
                f'        action_fqn={fqn!r},\n'
                f'        realized_method_fqn=_result_{i}.realized_method_fqn,\n'
                f'        dispatch_consistent=_result_{i}.dispatch_consistent,\n'
                f'        dispatch_mismatch_reason=_result_{i}.dispatch_mismatch_reason,\n'
                f'        duration_ms=_result_{i}.duration_ms,\n'
                f'    ))'
            )
        return "\n".join(lines) + "\n"


__all__ = ["PythonGenerator"]
