"""Generated by PythonGenerator (echo-stub, spec 05 §1.3 단순화).

ChangeSpec.action_fqn       : action.scm.슬랩설계_실행
RunPlan.estimated_steps     : 22
RunPlan.delegates_to_tree.size : 22

atomic_overrides:
  - action.scm.슬랩설계_실행.inputs[0]<scm.order.Order>.width = 1180
  - action.scm.슬랩설계_실행.inputs[0]<scm.order.Order>.thickness = 220

본 코드는 PythonGenerator 가 합성한 텍스트 — 직접 실행 금지.
sandbox 가 import 화이트리스트 검증 후 exec/ast-execute (spec 05 §1.4).
"""

from backend.shared.contracts.simulation import DelegationTraceFrame


def run(inputs, java_sandbox, lookup_source, run_options):
    """ECHO-STUB run() — orchestrator (3b-4) 가 보강 예정.

    Args:
        inputs           : RunInputs (slots / fixture / overrides / primary_input_slot)
        java_sandbox     : JavaSandbox 구현체 (StubJavaSandbox 등)
        lookup_source    : LookupDataSource 인스턴스
        run_options      : RunOptions

    Returns:
        dict — {"trace": list[DelegationTraceFrame], "outputs": dict}
    """
    trace: list = []
    # delegation frame 1 (depth=0) — echo-stub sequential
    _result_1 = java_sandbox.dispatch('action.scm.슬랩설계_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=0,
        action_fqn='action.scm.슬랩설계_실행',
        realized_method_fqn=_result_1.realized_method_fqn,
        dispatch_consistent=_result_1.dispatch_consistent,
        dispatch_mismatch_reason=_result_1.dispatch_mismatch_reason,
        duration_ms=_result_1.duration_ms,
    ))
    # delegation frame 2 (depth=1) — echo-stub sequential
    _result_2 = java_sandbox.dispatch('action.scm.order.정합성_검증', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.order.정합성_검증',
        realized_method_fqn=_result_2.realized_method_fqn,
        dispatch_consistent=_result_2.dispatch_consistent,
        dispatch_mismatch_reason=_result_2.dispatch_mismatch_reason,
        duration_ms=_result_2.duration_ms,
    ))
    # delegation frame 3 (depth=1) — echo-stub sequential
    _result_3 = java_sandbox.dispatch('action.scm.product.classify_by_product_code', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.product.classify_by_product_code',
        realized_method_fqn=_result_3.realized_method_fqn,
        dispatch_consistent=_result_3.dispatch_consistent,
        dispatch_mismatch_reason=_result_3.dispatch_mismatch_reason,
        duration_ms=_result_3.duration_ms,
    ))
    # delegation frame 4 (depth=1) — echo-stub sequential
    _result_4 = java_sandbox.dispatch('action.scm.resolve_and_set', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.resolve_and_set',
        realized_method_fqn=_result_4.realized_method_fqn,
        dispatch_consistent=_result_4.dispatch_consistent,
        dispatch_mismatch_reason=_result_4.dispatch_mismatch_reason,
        duration_ms=_result_4.duration_ms,
    ))
    # delegation frame 5 (depth=1) — echo-stub sequential
    _result_5 = java_sandbox.dispatch('action.scm.product.cumulative_productivity', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.product.cumulative_productivity',
        realized_method_fqn=_result_5.realized_method_fqn,
        dispatch_consistent=_result_5.dispatch_consistent,
        dispatch_mismatch_reason=_result_5.dispatch_mismatch_reason,
        duration_ms=_result_5.duration_ms,
    ))
    # delegation frame 6 (depth=1) — echo-stub sequential
    _result_6 = java_sandbox.dispatch('action.scm.thickness_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.thickness_실행',
        realized_method_fqn=_result_6.realized_method_fqn,
        dispatch_consistent=_result_6.dispatch_consistent,
        dispatch_mismatch_reason=_result_6.dispatch_mismatch_reason,
        duration_ms=_result_6.duration_ms,
    ))
    # delegation frame 7 (depth=1) — echo-stub sequential
    _result_7 = java_sandbox.dispatch('action.scm.width_range_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.width_range_실행',
        realized_method_fqn=_result_7.realized_method_fqn,
        dispatch_consistent=_result_7.dispatch_consistent,
        dispatch_mismatch_reason=_result_7.dispatch_mismatch_reason,
        duration_ms=_result_7.duration_ms,
    ))
    # delegation frame 8 (depth=1) — echo-stub sequential
    _result_8 = java_sandbox.dispatch('action.scm.length_range_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.length_range_실행',
        realized_method_fqn=_result_8.realized_method_fqn,
        dispatch_consistent=_result_8.dispatch_consistent,
        dispatch_mismatch_reason=_result_8.dispatch_mismatch_reason,
        duration_ms=_result_8.duration_ms,
    ))
    # delegation frame 9 (depth=1) — echo-stub sequential
    _result_9 = java_sandbox.dispatch('action.scm.first_weight_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.first_weight_실행',
        realized_method_fqn=_result_9.realized_method_fqn,
        dispatch_consistent=_result_9.dispatch_consistent,
        dispatch_mismatch_reason=_result_9.dispatch_mismatch_reason,
        duration_ms=_result_9.duration_ms,
    ))
    # delegation frame 10 (depth=1) — echo-stub sequential
    _result_10 = java_sandbox.dispatch('action.scm.second_wgt_low_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.second_wgt_low_실행',
        realized_method_fqn=_result_10.realized_method_fqn,
        dispatch_consistent=_result_10.dispatch_consistent,
        dispatch_mismatch_reason=_result_10.dispatch_mismatch_reason,
        duration_ms=_result_10.duration_ms,
    ))
    # delegation frame 11 (depth=1) — echo-stub sequential
    _result_11 = java_sandbox.dispatch('action.scm.second_wgt_high_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.second_wgt_high_실행',
        realized_method_fqn=_result_11.realized_method_fqn,
        dispatch_consistent=_result_11.dispatch_consistent,
        dispatch_mismatch_reason=_result_11.dispatch_mismatch_reason,
        duration_ms=_result_11.duration_ms,
    ))
    # delegation frame 12 (depth=1) — echo-stub sequential
    _result_12 = java_sandbox.dispatch('action.scm.max_split_count_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.max_split_count_실행',
        realized_method_fqn=_result_12.realized_method_fqn,
        dispatch_consistent=_result_12.dispatch_consistent,
        dispatch_mismatch_reason=_result_12.dispatch_mismatch_reason,
        duration_ms=_result_12.duration_ms,
    ))
    # delegation frame 13 (depth=1) — echo-stub sequential
    _result_13 = java_sandbox.dispatch('action.scm.split_range_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.split_range_실행',
        realized_method_fqn=_result_13.realized_method_fqn,
        dispatch_consistent=_result_13.dispatch_consistent,
        dispatch_mismatch_reason=_result_13.dispatch_mismatch_reason,
        duration_ms=_result_13.duration_ms,
    ))
    # delegation frame 14 (depth=1) — echo-stub sequential
    _result_14 = java_sandbox.dispatch('action.scm.slab.initial_slab_wgt_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.slab.initial_slab_wgt_실행',
        realized_method_fqn=_result_14.realized_method_fqn,
        dispatch_consistent=_result_14.dispatch_consistent,
        dispatch_mismatch_reason=_result_14.dispatch_mismatch_reason,
        duration_ms=_result_14.duration_ms,
    ))
    # delegation frame 15 (depth=1) — echo-stub sequential
    _result_15 = java_sandbox.dispatch('action.scm.slab.slab_wgt_recalc_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.slab.slab_wgt_recalc_실행',
        realized_method_fqn=_result_15.realized_method_fqn,
        dispatch_consistent=_result_15.dispatch_consistent,
        dispatch_mismatch_reason=_result_15.dispatch_mismatch_reason,
        duration_ms=_result_15.duration_ms,
    ))
    # delegation frame 16 (depth=1) — echo-stub sequential
    _result_16 = java_sandbox.dispatch('action.scm.slab.slab_count_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.slab.slab_count_실행',
        realized_method_fqn=_result_16.realized_method_fqn,
        dispatch_consistent=_result_16.dispatch_consistent,
        dispatch_mismatch_reason=_result_16.dispatch_mismatch_reason,
        duration_ms=_result_16.duration_ms,
    ))
    # delegation frame 17 (depth=1) — echo-stub sequential
    _result_17 = java_sandbox.dispatch('action.scm.final_width_range_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.final_width_range_실행',
        realized_method_fqn=_result_17.realized_method_fqn,
        dispatch_consistent=_result_17.dispatch_consistent,
        dispatch_mismatch_reason=_result_17.dispatch_mismatch_reason,
        duration_ms=_result_17.duration_ms,
    ))
    # delegation frame 18 (depth=1) — echo-stub sequential
    _result_18 = java_sandbox.dispatch('action.scm.final_length_range_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.final_length_range_실행',
        realized_method_fqn=_result_18.realized_method_fqn,
        dispatch_consistent=_result_18.dispatch_consistent,
        dispatch_mismatch_reason=_result_18.dispatch_mismatch_reason,
        duration_ms=_result_18.duration_ms,
    ))
    # delegation frame 19 (depth=1) — echo-stub sequential
    _result_19 = java_sandbox.dispatch('action.scm.target_width_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.target_width_실행',
        realized_method_fqn=_result_19.realized_method_fqn,
        dispatch_consistent=_result_19.dispatch_consistent,
        dispatch_mismatch_reason=_result_19.dispatch_mismatch_reason,
        duration_ms=_result_19.duration_ms,
    ))
    # delegation frame 20 (depth=1) — echo-stub sequential
    _result_20 = java_sandbox.dispatch('action.scm.target_length_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.target_length_실행',
        realized_method_fqn=_result_20.realized_method_fqn,
        dispatch_consistent=_result_20.dispatch_consistent,
        dispatch_mismatch_reason=_result_20.dispatch_mismatch_reason,
        duration_ms=_result_20.duration_ms,
    ))
    # delegation frame 21 (depth=1) — echo-stub sequential
    _result_21 = java_sandbox.dispatch('action.scm.slab.slab_save_실행', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.slab.slab_save_실행',
        realized_method_fqn=_result_21.realized_method_fqn,
        dispatch_consistent=_result_21.dispatch_consistent,
        dispatch_mismatch_reason=_result_21.dispatch_mismatch_reason,
        duration_ms=_result_21.duration_ms,
    ))
    # delegation frame 22 (depth=1) — echo-stub sequential
    _result_22 = java_sandbox.dispatch('action.scm.record_step', inputs, run_options)
    trace.append(DelegationTraceFrame(
        seq=len(trace) + 1,
        depth=1,
        action_fqn='action.scm.record_step',
        realized_method_fqn=_result_22.realized_method_fqn,
        dispatch_consistent=_result_22.dispatch_consistent,
        dispatch_mismatch_reason=_result_22.dispatch_mismatch_reason,
        duration_ms=_result_22.duration_ms,
    ))

    return {"trace": trace, "outputs": {}}
