#!/usr/bin/env python3
"""Generate Pydantic Patch models from the editable_fields YAML SSOT.

Reads:
    toClaude/modeling/editable_fields.yaml
Writes:
    backend/modeling/api/_generated_patch_models.py

Usage:
    python scripts/codegen_patch_models.py [--check]

The script is idempotent: re-running with no YAML change produces a byte-identical
file. With --check, exits non-zero if the on-disk file would change (CI gate).

Design notes:
- Driven entirely from YAML — no entity name is hardcoded here.
- Emits one Pydantic v2 BaseModel per entity, named per `patch_class`.
- Only fields whose `edit` is in EDITABLE_KINDS and `immutable: false` make it in.
- `derived_from` fields are skipped (display-only).
- `validation.one_of` becomes `Literal[...]`; min/max_length become Field constraints.
- The model gates list/dict columns: types come straight from YAML.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
YAML_PATH = REPO_ROOT / "toClaude/modeling/editable_fields.yaml"
OUT_PATH = REPO_ROOT / "backend/modeling/api/_generated_patch_models.py"

EDITABLE_KINDS = {
    "inline_text",
    "inline_textarea",
    "inline_list",
    "inline_select",
    "inline_autocomplete",
    "inline_number",
    "inline_range",
}

HEADER = '''\
"""AUTO-GENERATED BY scripts/codegen_patch_models.py — DO NOT EDIT.

Source of truth: toClaude/modeling/editable_fields.yaml
Regenerate with:  python scripts/codegen_patch_models.py
"""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

'''


def _python_type(yaml_type: str) -> str:
    """Pass-through with light normalization. Trust the YAML author."""
    t = yaml_type.strip()
    # Accept native python type literals; nothing else to translate.
    return t


def _field_type_expr(field_name: str, spec: dict[str, Any]) -> str:
    """Compute the Python type expression for a Patch field.

    For inline_select with `validation.one_of`, emit Literal[...].
    Otherwise use the declared `type` directly. Always Optional (PATCH semantics).
    """
    validation = spec.get("validation") or {}
    one_of = validation.get("one_of")
    edit = spec.get("edit")
    edit_opts = spec.get("edit_opts") or {}

    if edit == "inline_select" and one_of and not edit_opts.get("fallback_text"):
        # Strict enum — Literal locks it down at the API boundary.
        rendered = ", ".join(repr(v) for v in one_of)
        base = f"Literal[{rendered}]"
    else:
        base = _python_type(spec["type"])

    return f"{base} | None"


def _field_constraints(spec: dict[str, Any]) -> str:
    """Build the Field(...) call string. Returns '' if no constraints needed."""
    validation = spec.get("validation") or {}
    parts: list[str] = ["default=None"]

    if "min_length" in validation:
        parts.append(f"min_length={validation['min_length']}")
    if "max_length" in validation:
        parts.append(f"max_length={validation['max_length']}")
    if "regex" in validation:
        parts.append(f"pattern={validation['regex']!r}")

    return f"Field({', '.join(parts)})"


def _emit_entity(entity_name: str, entity_spec: dict[str, Any]) -> list[str]:
    patch_class = entity_spec["patch_class"]
    fields = entity_spec.get("fields") or {}

    lines: list[str] = []
    lines.append(f"class {patch_class}(BaseModel):")
    lines.append(f'    """PATCH body for {entity_name}. None = field unchanged."""')

    body: list[str] = []
    for field_name, spec in fields.items():
        edit = spec.get("edit")
        immutable = bool(spec.get("immutable"))
        derived = spec.get("derived_from")
        if immutable or derived or edit not in EDITABLE_KINDS:
            continue

        type_expr = _field_type_expr(field_name, spec)
        constraints = _field_constraints(spec)
        body.append(f"    {field_name}: {type_expr} = {constraints}")

    if not body:
        body.append("    pass")

    lines.extend(body)
    lines.append("")
    return lines


def render(yaml_data: dict[str, Any]) -> str:
    entities = yaml_data["entities"]
    out: list[str] = [HEADER]

    class_names: list[str] = []
    for entity_name, entity_spec in entities.items():
        out.extend(_emit_entity(entity_name, entity_spec))
        class_names.append(entity_spec["patch_class"])

    # ENTITY_TO_PATCH lookup table — used by Wave 2 to dispatch generically.
    out.append("# Generic dispatch table (entity_name → Patch class)")
    out.append("ENTITY_TO_PATCH = {")
    for entity_name, entity_spec in entities.items():
        out.append(f"    {entity_name!r}: {entity_spec['patch_class']},")
    out.append("}")
    out.append("")

    out.append("__all__ = (")
    for cls in class_names:
        out.append(f"    {cls!r},")
    out.append('    "ENTITY_TO_PATCH",')
    out.append(")")
    out.append("")

    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if regeneration would change the file.")
    args = parser.parse_args()

    if not YAML_PATH.exists():
        print(f"ERROR: YAML not found at {YAML_PATH}", file=sys.stderr)
        return 2

    with YAML_PATH.open("r", encoding="utf-8") as fp:
        data = yaml.safe_load(fp)

    rendered = render(data)

    if args.check:
        existing = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else ""
        if existing != rendered:
            print(f"ERROR: {OUT_PATH} is stale. Run: python scripts/codegen_patch_models.py",
                  file=sys.stderr)
            return 1
        print(f"OK  {OUT_PATH} up to date.")
        return 0

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"WROTE {OUT_PATH}  ({rendered.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
