#!/usr/bin/env python3
"""Generate the TypeScript inline-edit wiring helper from the YAML SSOT.

Reads:
    toClaude/modeling/editable_fields.yaml
Writes:
    frontend/src/lib/_generated/inline_wiring.ts

The output exposes:
    EDITABLE_FIELDS: typed map  EDITABLE_FIELDS[entity][field] = EditConfig
    EditConfig:      { kind, patch_key, edit_opts?, validation?, ... }
    getEditConfig(entity, field) -> EditConfig | null

This file is consumed (Wave 2) by MainPanel.tsx to drop the per-field
hand-wired props, and by InlineEdit.tsx to read confirm_modal / fallback_text /
autocomplete_source flags. Until Wave 2, the file just sits here for review.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
YAML_PATH = REPO_ROOT / "toClaude/modeling/editable_fields.yaml"
OUT_PATH = REPO_ROOT / "frontend/src/lib/_generated/inline_wiring.ts"

EDITABLE_KINDS = {
    "inline_text",
    "inline_textarea",
    "inline_list",
    "inline_select",
    "inline_autocomplete",
    "inline_number",
    "inline_range",
}

HEADER = """\
// AUTO-GENERATED BY scripts/codegen_inline_wiring.py — DO NOT EDIT.
// Source of truth: toClaude/modeling/editable_fields.yaml
// Regenerate with:  python scripts/codegen_inline_wiring.py

export type EditKind =
  | "inline_text"
  | "inline_textarea"
  | "inline_list"
  | "inline_select"
  | "inline_autocomplete"
  | "inline_number"
  | "inline_range"
  | "read_only"
  | "authoring_only";

export interface EditOpts {
  confirm_modal?: boolean;
  options?: string[];
  fallback_text?: boolean;
  autocomplete_source?: string;
  min?: number;
  max?: number;
  step?: number;
  rows?: number;
}

export interface ValidationOpts {
  min_length?: number;
  max_length?: number;
  regex?: string;
  one_of?: string[];
}

export interface EditConfig {
  kind: EditKind;
  /** key sent in the PATCH body (defaults to field name) */
  patch_key: string;
  /** ORM column name — diagnostic only, not used at runtime */
  backend_column: string;
  edit_opts?: EditOpts;
  validation?: ValidationOpts;
  /** if set, field is derived from another path; UI shows it read-only */
  derived_from?: string;
  /** for fields with auto + user-override duality (#8 CodeType.role) */
  confidence_label?: "auto" | "mixed" | "user_only";
}

export type EntityName =
"""


def _ts_value(value: Any) -> str:
    """Render a Python value as TypeScript / JSON literal."""
    return json.dumps(value, ensure_ascii=False)


def _config_object(field_name: str, spec: dict[str, Any]) -> dict[str, Any]:
    edit = spec.get("edit", "read_only")
    derived = spec.get("derived_from")
    immutable = bool(spec.get("immutable"))

    # read_only / authoring_only / immutable / derived → emit kind only.
    out: dict[str, Any] = {
        "kind": edit if not (immutable or derived) else "read_only",
        "patch_key": field_name,
        "backend_column": spec.get("backend_column", field_name),
    }

    if derived:
        out["derived_from"] = derived
    if spec.get("confidence_label"):
        out["confidence_label"] = spec["confidence_label"]

    edit_opts = spec.get("edit_opts")
    if edit_opts:
        # Only carry edit_opts when the field is actually editable inline.
        if out["kind"] in EDITABLE_KINDS:
            out["edit_opts"] = edit_opts

    validation = spec.get("validation")
    if validation:
        out["validation"] = validation

    return out


def render(yaml_data: dict[str, Any]) -> str:
    entities = yaml_data["entities"]
    entity_names = list(entities.keys())

    out: list[str] = [HEADER]

    # union of entity literals
    for i, name in enumerate(entity_names):
        suffix = ";" if i == len(entity_names) - 1 else ""
        out.append(f"  | {json.dumps(name)}{suffix}")
    out.append("")

    # The big record. We type it loosely as Record<string, EditConfig> per entity
    # because per-entity field unions would explode line count without value.
    out.append("export const EDITABLE_FIELDS: Record<EntityName, Record<string, EditConfig>> = {")
    for entity_name, entity_spec in entities.items():
        out.append(f"  {json.dumps(entity_name)}: {{")
        fields = entity_spec.get("fields") or {}
        for field_name, spec in fields.items():
            cfg = _config_object(field_name, spec)
            cfg_json = json.dumps(cfg, ensure_ascii=False, indent=2)
            # indent the JSON to match TS object nesting (4 leading spaces for inner,
            # 6 for the JSON body itself once we re-indent)
            indented = "\n".join(
                ("    " + line) if idx else line
                for idx, line in enumerate(cfg_json.splitlines())
            )
            out.append(f"    {json.dumps(field_name)}: {indented},")
        out.append("  },")
    out.append("};")
    out.append("")

    out.append("export function getEditConfig(")
    out.append("  entity: EntityName | string,")
    out.append("  field: string,")
    out.append("): EditConfig | null {")
    out.append("  const e = (EDITABLE_FIELDS as Record<string, Record<string, EditConfig>>)[entity];")
    out.append("  if (!e) return null;")
    out.append("  return e[field] ?? null;")
    out.append("}")
    out.append("")

    out.append("/** Convenience: list of all entities for iteration */")
    rendered_names = ", ".join(json.dumps(n) for n in entity_names)
    out.append(f"export const ENTITIES: ReadonlyArray<EntityName> = [{rendered_names}] as const;")
    out.append("")

    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if regeneration would change the file.")
    args = parser.parse_args()

    if not YAML_PATH.exists():
        print(f"ERROR: YAML not found at {YAML_PATH}", file=sys.stderr)
        return 2

    with YAML_PATH.open("r", encoding="utf-8") as fp:
        data = yaml.safe_load(fp)

    rendered = render(data)

    if args.check:
        existing = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else ""
        if existing != rendered:
            print(f"ERROR: {OUT_PATH} is stale. Run: python scripts/codegen_inline_wiring.py",
                  file=sys.stderr)
            return 1
        print(f"OK  {OUT_PATH} up to date.")
        return 0

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"WROTE {OUT_PATH}  ({rendered.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
