<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.example.slabdesign</groupId>
        <artifactId>slab-design-v2</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>slab-design-boot</artifactId>
    <name>slab-design-boot</name>
    <dependencies>
        <dependency>
            <groupId>com.example.slabdesign</groupId>
            <artifactId>slab-design-facade</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.example.slabdesign.boot.SlabDesignApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
